// Code generated by cmd/generate-tests from REOLINK_E1_Zoom_v3.1.0.2649_23083101_xmlcapture_20260113-134015.tar.gz; DO NOT EDIT.

package onvif_test

import (
	"context"
	"testing"
	"time"

	"github.com/0x524a/onvif-go"
	onviftesting "github.com/0x524a/onvif-go/testing"
)

// TestREOLINK_E1_Zoom_v3102649_23083101 tests ONVIF client against REOLINK E1 Zoom (Firmware: v3.1.0.2649_23083101) captured responses.
// Capture format: V2 with parameter-aware matching
// Total captured operations: 16
func TestREOLINK_E1_Zoom_v3102649_23083101(t *testing.T) {
	// Load capture archive (relative to project root)
	captureArchive := "REOLINK_E1_Zoom_v3.1.0.2649_23083101_xmlcapture_20260113-134015.tar.gz"

	mockServer, err := onviftesting.NewMockSOAPServerV2(captureArchive)
	if err != nil {
		t.Fatalf("Failed to create mock server: %v", err)
	}
	defer mockServer.Close()

	// Create ONVIF client pointing to mock server
	client, err := onvif.NewClient(
		mockServer.URL()+"/onvif/device_service",
		onvif.WithCredentials("testuser", "testpass"),
	)
	if err != nil {
		t.Fatalf("Failed to create ONVIF client: %v", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	// =========================================================================
	// Device Service Operations
	// =========================================================================

	t.Run("GetCapabilities", func(t *testing.T) {
		caps, err := client.GetCapabilities(ctx)
		if err != nil {
			t.Errorf("GetCapabilities failed: %v", err)
			return
		}
		t.Logf("Capabilities: Device=%v, Media=%v, Imaging=%v, PTZ=%v",
			caps.Device != nil, caps.Media != nil, caps.Imaging != nil, caps.PTZ != nil)
	})

	t.Run("GetDeviceInformation", func(t *testing.T) {
		info, err := client.GetDeviceInformation(ctx)
		if err != nil {
			t.Errorf("GetDeviceInformation failed: %v", err)
			return
		}
		if info.Manufacturer == "" {
			t.Error("Manufacturer is empty")
		}
		if info.Model == "" {
			t.Error("Model is empty")
		}
		t.Logf("Device: %s %s (Firmware: %s)", info.Manufacturer, info.Model, info.FirmwareVersion)
	})

	t.Run("GetSystemDateAndTime", func(t *testing.T) {
		_, err := client.GetSystemDateAndTimeTyped(ctx)
		if err != nil {
			t.Errorf("GetSystemDateAndTime failed: %v", err)
		}
	})

	// =========================================================================
	// Media Service Operations
	// =========================================================================

	// Initialize to discover service endpoints (required for Media/PTZ/Imaging)
	if err := client.Initialize(ctx); err != nil {
		t.Fatalf("Failed to initialize client: %v", err)
	}

	t.Run("GetProfiles", func(t *testing.T) {
		profiles, err := client.GetProfiles(ctx)
		if err != nil {
			t.Errorf("GetProfiles failed: %v", err)
			return
		}
		if len(profiles) == 0 {
			t.Error("No profiles returned")
		}
		t.Logf("Found %d profile(s)", len(profiles))
	})

	// =========================================================================
	// Profile-Dependent Operations
	// =========================================================================

	// =========================================================================
	// PTZ Operations
	// =========================================================================

	t.Run("PTZ_GetPresets_000", func(t *testing.T) {
		presets, err := client.GetPresets(ctx, "000")
		if err != nil {
			t.Errorf("GetPresets failed: %v", err)
			return
		}
		t.Logf("Found %d preset(s) for profile 000", len(presets))
	})

	t.Run("PTZ_GetPresets_001", func(t *testing.T) {
		presets, err := client.GetPresets(ctx, "001")
		if err != nil {
			t.Errorf("GetPresets failed: %v", err)
			return
		}
		t.Logf("Found %d preset(s) for profile 001", len(presets))
	})

	t.Run("PTZ_GetStatus_000", func(t *testing.T) {
		status, err := client.GetStatus(ctx, "000")
		if err != nil {
			t.Errorf("GetStatus failed: %v", err)
			return
		}
		t.Logf("PTZ Status retrieved for profile 000")
		_ = status
	})

	t.Run("PTZ_GetStatus_001", func(t *testing.T) {
		status, err := client.GetStatus(ctx, "001")
		if err != nil {
			t.Errorf("GetStatus failed: %v", err)
			return
		}
		t.Logf("PTZ Status retrieved for profile 001")
		_ = status
	})

	// =========================================================================
	// Imaging Operations
	// =========================================================================

	t.Run("GetImagingSettings_000", func(t *testing.T) {
		settings, err := client.GetImagingSettings(ctx, "000")
		if err != nil {
			t.Errorf("GetImagingSettings failed: %v", err)
			return
		}
		t.Logf("Imaging settings retrieved for source 000")
		_ = settings
	})

}
