codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 45%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "cmd/**/*"
  - "examples/**/*"
  - "server/**/*"
  - "testing/**/*"
  - "**/*_test.go"
  - "*.md"
