name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Connect to camera at...
        2. Call method...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Minimal code sample to reproduce the issue
      render: go
      placeholder: |
        package main
        
        import "github.com/0x524a/onvif-go"
        
        func main() {
            // Your code here
        }

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: Output of `go version`
      placeholder: go version go1.21.0 linux/amd64
    validations:
      required: true

  - type: input
    id: lib-version
    attributes:
      label: Library Version
      description: Git commit hash or release version
      placeholder: v1.0.0 or commit abc123

  - type: input
    id: camera
    attributes:
      label: Camera Model/Brand
      description: If applicable
      placeholder: Hikvision DS-2CD2xx, Axis M1065-L, etc.

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Output/Logs
      description: Paste any error messages or logs
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the problem
