#!/bin/bash
# gen-third-party-notices.sh - Write THIRD_PARTY_NOTICES.md for the code that is
# compiled into the library and the command-line tools.
#
# MIT and BSD licenses ask for their copyright notice to accompany binary
# redistribution, so release archives ship this file. Only modules that are
# actually built in are listed (not everything in the module graph), and the
# script fails if a module has no license file, so a new dependency cannot slip
# in unnoticed.
#
# Usage: scripts/gen-third-party-notices.sh [output-file]

set -euo pipefail

# Run from the repository root whatever the caller's working directory.
cd "$(dirname "${BASH_SOURCE[0]}")/.."

OUT=${1:-THIRD_PARTY_NOTICES.md}

modules=$(go list -deps -f '{{with .Module}}{{if not .Main}}{{.Path}}|{{.Version}}|{{.Dir}}{{end}}{{end}}' \
    . ./discovery ./server ./cmd/... | sort -u)

{
    echo "# Third-party notices"
    echo
    echo "onvif-go is released under the MIT License (see LICENSE). It includes or links the"
    echo "following third-party modules, each under the license reproduced below."
    echo
    echo "Generated by scripts/gen-third-party-notices.sh. Do not edit by hand."

    while IFS='|' read -r path version dir; do
        license=""
        for name in LICENSE LICENSE.md LICENSE.txt LICENCE COPYING; do
            if [ -f "$dir/$name" ]; then
                license="$dir/$name"
                break
            fi
        done

        if [ -z "$license" ]; then
            echo "error: no license file found for $path $version" >&2
            exit 1
        fi

        echo
        echo "## $path $version"
        echo
        echo '```text'
        cat "$license"
        echo
        echo '```'
    done <<< "$modules"
} > "$OUT"

echo "Wrote $OUT ($(grep -c '^## ' "$OUT") modules)"
