name: Documentation

on:
  push:
    branches: [ master, main ]
    paths:
      - 'docs/**'
      - '*.md'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docs-check:
    name: Documentation Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      
      - name: Check for broken links
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.3.0
        with:
          args: --verbose --no-progress docs/ *.md
        continue-on-error: true
      
      - name: Validate markdown
        uses: DavidAnson/markdownlint-cli2-action@21c1be1b93ad9ed58fa840aacc3f279cde2a72ff # v24.2.0
        with:
          globs: 'docs/**/*.md'
        continue-on-error: true
